package provider

import (
	"context"
	"strings"
)

// RowClassificationInput encapsulates raw/normalized row features for AI inference.
type RowClassificationInput struct {
	RawName         string  `json:"rawName"`
	RawCode         string  `json:"rawCode"`
	RawCategory     string  `json:"rawCategory"`
	RawManufacturer string  `json:"rawManufacturer"`
	RawSupplier     string  `json:"rawSupplier"`
	UnitCost        float64 `json:"unitCost"`
	Currency        string  `json:"currency"`
	FileName        string  `json:"fileName"`
	SheetName       string  `json:"sheetName"`
}

// AIClassificationOutput represents advisory suggestions generated by the AI co-pilot.
type AIClassificationOutput struct {
	NormalizedName       string  `json:"normalizedName"`
	ItemClassification   string  `json:"itemClassification"`   // PRODUCT, COMPONENT, SPARE_PART, ACCESSORY, SERVICE, CONSUMABLE, OTHER
	ProductType          string  `json:"productType"`          // TRADING, PROJECT, RND (when PRODUCT)
	SuggestedCategory    string  `json:"suggestedCategory"`
	SuggestedTargetTable string  `json:"suggestedTargetTable"` // products, components, service_items
	ConfidenceScore      float64 `json:"confidenceScore"`      // 0.0 - 100.0
	Reasoning            string  `json:"reasoning"`
	Status               string  `json:"status"`               // COMPLETED, AI_UNAVAILABLE
}

// AIClassificationProvider defines the vendor-agnostic interface for AI classification.
type AIClassificationProvider interface {
	SuggestClassification(ctx context.Context, input RowClassificationInput) (*AIClassificationOutput, error)
}

// HeuristicRuleAIClassifier implements an enterprise deterministic + heuristic NLP classifier.
type HeuristicRuleAIClassifier struct{}

func NewHeuristicRuleAIClassifier() *HeuristicRuleAIClassifier {
	return &HeuristicRuleAIClassifier{}
}

func (h *HeuristicRuleAIClassifier) SuggestClassification(ctx context.Context, input RowClassificationInput) (*AIClassificationOutput, error) {
	nameLower := strings.ToLower(input.RawName)
	catLower := strings.ToLower(input.RawCategory)
	codeLower := strings.ToLower(input.RawCode)
	fileLower := strings.ToLower(input.FileName)

	out := &AIClassificationOutput{
		NormalizedName:       strings.TrimSpace(input.RawName),
		ItemClassification:   "PRODUCT",
		ProductType:          "TRADING",
		SuggestedCategory:    "General Hardware",
		SuggestedTargetTable: "products",
		ConfidenceScore:      85.0,
		Status:               "COMPLETED",
	}

	// 1. Check for Service / Labor / Mobilization / Calibration / Operational Expenses
	if strings.Contains(nameLower, "kalibrasi") || strings.Contains(nameLower, "calibration") ||
		strings.Contains(nameLower, "instalasi") || strings.Contains(nameLower, "installation") ||
		strings.Contains(nameLower, "jasa") || strings.Contains(nameLower, "service") ||
		strings.Contains(nameLower, "mobilisasi") || strings.Contains(nameLower, "mobilization") ||
		strings.Contains(nameLower, "maintenance") || strings.Contains(nameLower, "perawatan") ||
		strings.Contains(nameLower, "cleaning") || strings.Contains(nameLower, "pembersihan") ||
		strings.Contains(nameLower, "validasi") || strings.Contains(nameLower, "validation") ||
		strings.Contains(nameLower, "perbaikan") || strings.Contains(nameLower, "repair") ||
		strings.Contains(nameLower, "support") || strings.Contains(nameLower, "teknisi") ||
		strings.Contains(nameLower, "engineering") || strings.Contains(nameLower, "transportasi") ||
		strings.Contains(nameLower, "transport") || strings.Contains(nameLower, "hotel") ||
		strings.Contains(nameLower, "meal") || strings.Contains(nameLower, "akomodasi") ||
		strings.Contains(nameLower, "konsumsi") || strings.Contains(nameLower, "kunjungan") ||
		strings.Contains(catLower, "service") || strings.Contains(catLower, "jasa") {
		out.ItemClassification = "SERVICE"
		out.ProductType = ""
		out.SuggestedCategory = "Engineering Services"
		out.SuggestedTargetTable = "service_items"
		out.ConfidenceScore = 96.0
		out.Reasoning = "Operational service, maintenance, calibration, site labor, or trip accommodation. Not a physical inventory item."
		return out, nil
	}

	// 2. Check for Finished Products & Instruments (Sensors, Probes, Gateways, Loggers, Panels, Transmitters, Analyzers, Calorimeters, Lab Equipment)
	// All finished instruments & commercial hardware are finished trading products.
	if strings.Contains(nameLower, "sensor") || strings.Contains(nameLower, "probe") ||
		strings.Contains(nameLower, "photonic") || strings.Contains(nameLower, "aquas") ||
		strings.Contains(nameLower, "ammonium") || strings.Contains(nameLower, "gateway") ||
		strings.Contains(nameLower, "hub") || strings.Contains(nameLower, "logger") ||
		strings.Contains(nameLower, "station") || strings.Contains(nameLower, "tracker") ||
		strings.Contains(nameLower, "transducer") || strings.Contains(nameLower, "transmitter") ||
		strings.Contains(nameLower, "analyzer") || strings.Contains(nameLower, "sparing") ||
		strings.Contains(nameLower, "panel") || strings.Contains(nameLower, "smart") ||
		strings.Contains(nameLower, "calorimeter") || strings.Contains(nameLower, "calorific") ||
		strings.Contains(nameLower, "oxygen bomb") || strings.Contains(nameLower, "bomb") ||
		strings.Contains(nameLower, "envilife") || strings.Contains(nameLower, "apparatus") ||
		strings.Contains(nameLower, "spectrophotometer") || strings.Contains(nameLower, "incubator") ||
		strings.Contains(nameLower, "centrifuge") || strings.Contains(nameLower, "microscope") ||
		strings.Contains(nameLower, "machine") || strings.Contains(nameLower, "tester") ||
		strings.Contains(nameLower, "meter") || strings.Contains(nameLower, "detector") ||
		strings.Contains(nameLower, "device") || strings.Contains(nameLower, "equipment") ||
		strings.Contains(nameLower, "instrument") || strings.Contains(nameLower, "automatic") ||
		strings.Contains(codeLower, "prd") || strings.Contains(codeLower, "gw") ||
		strings.Contains(codeLower, "sen") || strings.Contains(nameLower, "system") {
		out.ItemClassification = "PRODUCT"

		// Dynamic Context-Aware Product Type inference:
		if strings.Contains(fileLower, "bom") || strings.Contains(fileLower, "rnd") ||
			strings.Contains(fileLower, "schematic") || strings.Contains(codeLower, "rnd") {
			out.ProductType = "RND"
			out.Reasoning = "Identified as an In-House R&D engineering product."
		} else {
			out.ProductType = "TRADING"
			out.Reasoning = "Identified as commercially sourced finished product/instrument."
		}

		if strings.Contains(nameLower, "gateway") {
			out.SuggestedCategory = "Edge Gateways"
		} else if strings.Contains(nameLower, "sensor") || strings.Contains(nameLower, "probe") || strings.Contains(nameLower, "photonic") || strings.Contains(nameLower, "aquas") {
			out.SuggestedCategory = "Sensors & Nodes"
		} else if strings.Contains(nameLower, "tracker") {
			out.SuggestedCategory = "Asset Tracking"
		} else {
			out.SuggestedCategory = "Integrated Solutions"
		}
		out.SuggestedTargetTable = "products"
		out.ConfidenceScore = 95.0
		return out, nil
	}

	// 3. Check for Accessories & Cabling (Cables, Brackets, Power Supply Adapters, Antennas)
	if strings.Contains(nameLower, "kabel") || strings.Contains(nameLower, "cable") ||
		strings.Contains(nameLower, "antenna") || strings.Contains(nameLower, "antena") ||
		strings.Contains(nameLower, "bracket") || strings.Contains(nameLower, "enclosure") ||
		strings.Contains(nameLower, "adaptor") || strings.Contains(nameLower, "power supply") ||
		strings.Contains(nameLower, "casing") || strings.Contains(nameLower, "mounting") {
		out.ItemClassification = "ACCESSORY"
		out.ProductType = "TRADING"
		out.SuggestedCategory = "Accessories & Enclosures"
		out.SuggestedTargetTable = "products"
		out.ConfidenceScore = 91.0
		out.Reasoning = "Peripheral accessory, cabling harness, power adapter, or structural enclosure."
		return out, nil
	}

	// 4. Check strictly for Raw Electronic Components (Bare PCB, Resistors, Capacitors, ICs, Microcontrollers, LCD Panel)
	if strings.Contains(nameLower, "stm32") || strings.Contains(nameLower, "esp32") ||
		strings.Contains(nameLower, "atmega") || strings.Contains(nameLower, "microcontroller") ||
		strings.Contains(nameLower, "mcu") || strings.Contains(nameLower, "resistor") ||
		strings.Contains(nameLower, "capacitor") || strings.Contains(nameLower, "kapasitor") ||
		strings.Contains(nameLower, "diode") || strings.Contains(nameLower, "dioda") ||
		strings.Contains(nameLower, "mosfet") || strings.Contains(nameLower, "transistor") ||
		strings.Contains(nameLower, "ic ") || strings.Contains(nameLower, "chipset") ||
		strings.Contains(nameLower, "terminal block") || strings.Contains(nameLower, "header pin") ||
		strings.Contains(nameLower, "bare pcb") || strings.Contains(nameLower, "pcb ") ||
		strings.Contains(nameLower, "res ") || strings.Contains(nameLower, "cap ") ||
		strings.Contains(nameLower, "inductor") || strings.Contains(nameLower, "induktor") ||
		strings.Contains(nameLower, "lcd panel") || strings.Contains(nameLower, "oled panel") ||
		strings.Contains(nameLower, "crystal oscillator") || strings.Contains(nameLower, "relay module") ||
		strings.Contains(catLower, "semiconductor") || strings.Contains(catLower, "passive") {
		out.ItemClassification = "COMPONENT"
		out.ProductType = ""
		out.SuggestedCategory = "Microcontrollers & ICs"
		if strings.Contains(nameLower, "resistor") || strings.Contains(nameLower, "capacitor") || strings.Contains(nameLower, "kapasitor") {
			out.SuggestedCategory = "Passive Components"
		} else if strings.Contains(nameLower, "pcb") {
			out.SuggestedCategory = "Bare PCBs & Modules"
		}
		out.SuggestedTargetTable = "components"
		out.ConfidenceScore = 94.0
		out.Reasoning = "Raw electronic component or semiconductor building block for BOM assembly."
		return out, nil
	}

	// 5. Default fallback based on document context -> PRODUCT (TRADING)
	if strings.Contains(fileLower, "bom") || strings.Contains(fileLower, "rnd") {
		out.ProductType = "RND"
	} else {
		out.ProductType = "TRADING"
	}
	out.ItemClassification = "PRODUCT"
	out.SuggestedTargetTable = "products"
	out.Reasoning = "General hardware product item."

	return out, nil
}
